# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "batch-process-predict"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "batch-process-predict"
    dns_sd_configs:
      - names: ["batch-process-predict"]
        port: 8000
        type: A
        refresh_interval: 5s
